/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cataloog2;

//import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.DTDConstants;
import oracle.jrockit.jfr.events.Bits;

/**
 *
 * @author LUUQUAN-PC
 */
public class catalog extends javax.swing.JFrame {

    /**
     * Creates new form catalog
     */
    int codenumber;
   int subtitle;
   boolean checkbox;
   boolean update=false;
   boolean delete=false;
   boolean addnew=false;
   Connection con1;
    public catalog() {
        initComponents();
       jComboBox2.setVisible(false);
       jButton4.setEnabled(false);
       jButton5.setEnabled(false);
    }
   public void codenumber(){
       try {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           String durl = "jdbc:sqlserver://DESKTOP-AFNU90C\\SQLEXPRESS:1433;databaseName=DVDcatalog;user=luuquan;password=luuquan";
           Connection con = DriverManager.getConnection(durl);
           Statement s = con.createStatement();
           ResultSet rs=  s.executeQuery("select Max(DVDcodenumber) from DVD");
           while(rs.next()){
               
               codenumber=rs.getInt(1);
           }
 //          ResultSet
           
           
           
       } catch (Exception e) {
           codenumber=0;
       }
       codenumber++;
       String code= String.valueOf(codenumber);
       jTextField1.setText(code);
    }
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DVD catalogs");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DVD code number:");

        jTextField1.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("DVD title:");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Language");
        jLabel4.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Viet nam", "Spanlish", "French", "English" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Price:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Subtitles"));

        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton2)
                .addComponent(jRadioButton1))
        );

        jButton1.setText("Add new");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Detele");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cannel");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton7.setText("Gettable");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Disconnect");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Get connection");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 97, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(83, 83, 83)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  //      jComboBox1.setSelectedIndex(3);
        codenumber();
        addnew=true;
        update=false;
        delete=false;
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
        if(jRadioButton1.isSelected()){
            subtitle=1;
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2.isSelected()){
            subtitle=0;
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    
    public void dotable(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String durl="jdbc:sqlserver://DESKTOP-AFNU90C\\SQLEXPRESS:1433;databaseName=DVDcatalog;user=luuquan;password=luuquan";
            Connection con = DriverManager.getConnection(durl);
            Statement s = con.createStatement();
            ResultSet rs= s.executeQuery("select * from DVD");
            DefaultTableModel m = new DefaultTableModel(new Object[]{"DVDcodenumber","DVDtitle","Language","DVDsubtitle","DVDprice"},0);
            jTable1.setModel(m);
            while(rs.next()){
                ((DefaultTableModel)jTable1.getModel()).addRow(new Object[] {rs.getInt(1),rs.getString(2),rs.getString(3),rs.getInt(4),
                    rs.getInt(5)}
                );
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            
        if (update==true){
           try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String durl ="jdbc:sqlserver://DESKTOP-AFNU90C\\SQLEXPRESS:1433;databaseName=DVDcatalog;user=luuquan;password=luuquan ";
            Connection con = DriverManager.getConnection(durl);
       //     Statement s= con.createStatement();
            PreparedStatement ps= con.prepareStatement("Update DVD set DVDtitle=?,Language=?,DVDsubtitle=?,DVDprice=? where DVDcodenumber="+
                    jComboBox2.getSelectedItem().toString()+"");
            ps.setString(1, jTextField2.getText());
            ps.setString(2, jComboBox1.getSelectedItem().toString());
            ps.setInt(3, subtitle);
            ps.setString(4, jSpinner1.getValue().toString());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cap nhat thanh cong");
            jButton2.setEnabled(true);
            dotable();
            dotextf();
           } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Cap thanh khong thanh cong");
        }
    }
        if(delete==true){
               try {
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String diString= "jdbc:sqlserver://DESKTOP-AFNU90C\\SQLEXPRESS:1433;databaseName=DVDcatalog;user=luuquan;password=luuquan";
             Connection con = DriverManager.getConnection(diString);
           //  Statement s= con.createStatement();
          //   ResultSet rs = s.executeQuery("Delete DVD where DVDcodenumber="+jComboBox2.getSelectedItem().toString()+"");
             PreparedStatement ps = con.prepareStatement("Delete DVD where DVDcodenumber="+jComboBox2.getSelectedItem().toString()+"");
             ps.executeUpdate();
             JOptionPane.showMessageDialog(this, "Xoa thanh cong");
             jButton3.setEnabled(true);
             dotable();
             dotextf();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xoa khong thanh cong");
        }
        
        
            
        }

        if (addnew==true){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String durl = "jdbc:sqlserver://DESKTOP-AFNU90C\\SQLEXPRESS:1433;databaseName=DVDcatalog;user=luuquan;password=luuquan";
            Connection con = DriverManager.getConnection(durl);
            String truyvan = "Insert into DVD values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(truyvan);
            String code= String.valueOf(codenumber);
            pst.setString(1, code);
            pst.setString(2, jTextField2.getText());
            pst.setString(3, jComboBox1.getSelectedItem().toString());
            pst.setInt(4, subtitle);
            String s=String.valueOf(jSpinner1.getValue().toString());
            pst.setString(5, s);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Them thanh cong");
            dotable();
            dotextf();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Them khong thanh cong");
        }
        
        }
            
    }//GEN-LAST:event_jButton4ActionPerformed

    public void insertdata(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String durl="jdbc:sqlserver://DESKTOP-AFNU90C\\SQLEXPRESS:1433;databaseName=DVDcatalog;user=luuquan;password=luuquan";
            Connection con = DriverManager.getConnection(durl);
            Statement s= con.createStatement();
            ResultSet rs= s.executeQuery(" Select * from DVD where DVDcodenumber="+jComboBox2.getSelectedItem()+"");
            
            while(rs.next()){
             //   jTextField1.setText(jco);
                jTextField2.setText(rs.getString(2));
             //   jComboBox1.setSelectedItem(rs.getString(3).toString());
                jTextField3.setText(rs.getString(3).toString());
           //    int c;
           //    String d;
         //      d=rs.getString(3).toString();
             
                jSpinner1.setValue(rs.getInt(5));
                if (rs.getInt(4)==1){
                    jRadioButton1.setSelected(true);
                    jRadioButton2.setSelected(false);
                }
                if(rs.getInt(4)==0){
                    jRadioButton1.setSelected(false);
                    jRadioButton2.setSelected(true);
                }
            }
            con.close();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Do khong thanh cong");
        }
       
        
        
        
        
    }
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
 //      if (jCheckBox1.isSelected()){
        insertdata();
     
 //      }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             jButton4.setEnabled(true);
            jButton5.setEnabled(true);    
            jComboBox2.setVisible(true);
             Docombox();   
              jButton2.setEnabled(false);
              update=true; 
              addnew=false;
              delete=false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setEnabled(false);
        delete=true;
        jComboBox2.setVisible(true);
       Docombox();       
       addnew=false;
       update= false;
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton1.setEnabled(true);
       boolean update=false;
       boolean delete=false;
       boolean addnew=false;
       jComboBox2.setVisible(false);
       jTextField1.setText("");
       jTextField2.setText("");
       jComboBox1.setSelectedIndex(0);
    //   string b=0;
       String b="0";
       int a= Integer.valueOf(b);
       jSpinner1.setValue(a);
       jRadioButton1.setSelected(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                dotable();
                dotextf();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        dotextf();
        int i= jTable1.getSelectedRow();
        DefaultTableModel mode1= (DefaultTableModel)jTable1.getModel();
        jTextField1.setText(mode1.getValueAt(i, 0).toString());
        jTextField2.setText(mode1.getValueAt(i, 1).toString());
        String gg = mode1.getValueAt(i, 2).toString();
        jComboBox1.setSelectedItem(gg);
        float g= Float.parseFloat(mode1.getValueAt(i, 4).toString());
        jSpinner1.setValue(g);
        String subtitle = mode1.getValueAt(i, 3).toString();
        jTextField3.setText(gg);
        int sub = Integer.valueOf(subtitle);
        if (sub==1){
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
        }
        if (sub==0){
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(true);
        }
              
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String durl ="jdbc:sqlserver://DESKTOP-AFNU90C\\SQLEXPRESS:1433;databaseName=DVDcatalog;user=luuquan;password=luuquan";
             con1 = DriverManager.getConnection(durl);
            
            JOptionPane.showMessageDialog(this, "Ket noi thanh cong");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            if (con1 == null){
                return;
            }
            con1.close();
            JOptionPane.showMessageDialog(this, "Da huy ket noi thanh cong");
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    
    
    public void dotextf(){
        try {
            if (con1 == null || con1.isClosed()){
                JOptionPane.showMessageDialog(this, "Chua duoc ket noi");
                return;
            }
             Statement s = con1.createStatement();
             ResultSet rs = s.executeQuery("Select * from DVD");
             String s1="";
             while(rs.next()){
                 s1=s1+"DVDcodenumber "+rs.getInt(1)+"DVDtitle " +rs.getString(2)+"Language "+rs.getString(3)+"DVDsubtitle "+rs.getInt(4)+"DVDprice "+rs.getInt(5)+"\n";
                 
             }
             jTextArea1.setText(s1);
             
           // Statement s = DriverManager.
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
            
    
    public void Docombox(){
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String durl = "jdbc:sqlserver://DESKTOP-AFNU90C\\SQLEXPRESS;databaseName=DVDcatalog;user=luuquan;password=luuquan";
            Connection con = DriverManager.getConnection(durl);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select DVDcodenumber from DVD");
            
            while(rs.next()){
                //rs.getInt(durl);
                int a= rs.getInt(1);
                String aa = String.valueOf(a);
                jComboBox2.addItem(aa);
            }
        } catch (Exception e) {
           
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
